language: java
dist: xenial
jdk: openjdk10
before_install:
# https://joerglenhard.wordpress.com/2013/10/01/using-travis-ci-with-gradle-wrapper
 - chmod +x gradlew
# http://ecmendenhall.github.io/blog/blog/2013/05/28/two-travis-ci-solutions/
# enable GUI subsystem, otherwise we can't test the Swing parts (java.awt.HeadlessException)
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

env:
- TERM=dumb

script:
  - chmod +x ./gradlew
  
  - cd TaskOne
  - javac BasicGui.java
  - java Program 
  - cd ..
